export enum AvailableWidget {
  classicMenu = "classicMenu",
  featured = "featured",
  bookNow = "bookNow",
}

export enum AvailableIcons {
  chevronLeft = "chevronLeft",
  chevronDown = "chevronDown",
  magnifyingGlass = "magnifyingGlass",
  phone = "phone",
  xMark = "xMark",
  chartPie = "chartPie",
  cursorArrowRays = "cursorArrowRays",
  fingerPrint = "fingerPrint",
  squaresPlus = "squaresPlus",
  playCircle = "playCircle",
  rectangleGroup = "rectangleGroup",
  websiteDevelopment = "websiteDevelopment",
  applicationDevelopment = "applicationDevelopment",
  mobileDevelopment = "mobileDevelopment",
  alDevelopment = "alDevelopment",
  databaseDevelopment = "databaseDevelopment",
  platformDevelopment = "platformDevelopment",
  uiUXDesign = "uiUXDesign",
  videoProduction = "videoProduction",
  cloudAndInfrastructure = "cloudAndInfrastructure",
  otherSSWService = "otherSSWService",
  sugarLearning = "sugarLearning",
  timePro = "timePro",
  codeAuditor = "codeAuditor",
  linkAuditor = "linkAuditor",
  smashingBarrier = "smashingBarrier",
  sophieBot = "sophieBot",
  sophieHub = "sophieHub",
  sswRewards = "sswRewards",
}
