name: 📄 New Webpage
description: Start here to request a new page
title: "📄 {{ TITLE }} "
body:
  - type: markdown
    attributes:
      value: |
        @camillars @sethdailyssw
        Fill out the below fields with information about your new page:
  - type: input
    id: cc
    attributes:
      label: "1. People in the loop:"
      description: "@ tag the people involved/cc'd"
      placeholder: "{{ PERSON THIS TASK IS FROM }}, {{ PERSON YOU ARE GIVING THIS TASK }}"
      value: 
    validations:
      required: true
  - type: input
    id: template
    attributes:
      label: "2. Page template to copy:"
      description: Link a design template or a page to copy (e.g. a Consulting page or a Training page).
      placeholder: "{{ PAGE TEMPLATE LINK }}"
      value:
    validations:
      required: true
  - type: input
    id: CRM
    attributes:
      label: "3. Consulting Service in CRM:"
      description: Link the matching [consulting service from CRM](https://ssw.crm6.dynamics.com/main.aspx?appid=05daa2a9-8768-446e-b9d3-580c8a6f9b8b&pagetype=entitylist&etn=ssw_consultingservice&viewid=b400b0b8-363d-404b-bbd5-d56343c21d1f&viewType=1039). If there is no existing one for this page, you should create one. This is because each consulting page on the website needs a matching consulting service record in CRM. If you are not requesting a consulting page, write N/A.
      placeholder: "{{ CONSULTING SERVICE URL FROM CRM }}"
      value:
    validations:
      required: true
  - type: input
    id: URI
    attributes:
      label: "4. URI:"
      description: "Details: Concise and including keywords. Use [kebab case](https://www.ssw.com.au/rules/use-dashes-in-urls) (e.g. use-dashes-and-lowercase). 
      
      Length: [As short as possible](https://www.ssw.com.au/rules/create-friendly-short-urls/)"
      placeholder: "{{ URI }}"
      value:
    validations:
      required: true
  - type: input
    id: title
    attributes:
      label: "5. Title:"
      description: "Details: Must read well and include keywords (Google-able).
      
      Length: Must be under 60 characters"  
      placeholder: "{{ TITLE }}"
      value:
    validations:
      required: true
  - type: textarea
    id: meta
    attributes:
      label: "6. Meta description:"
      description: "Details: For search engines - summary of the page using the important keywords.
      
      Length: under 150 characters. 
      
      Tip: You can give ChatGPT your content and ask for a meta description."
      placeholder: "{{ META DESCRIPTION }}"
      value:
    validations:
      required: true
  - type: textarea
    id: related
    attributes:
      label: "7. Related URLs:"
      description: If applicable, related pages on the SSW website.
      placeholder: "{{ RELATED URLS }}"
      value:
    validations:
      required: true
  - type: textarea
    id: content
    attributes:
      label: "8. Content:"
      description: "Follow these guidelines:  

      
      **Headings** – Next to each heading, note in (parentheses) an HTML title tag - H1 for the main title (only 1 per page) H2 for subheadings, H3 etc... Each heading must include keywords.  
        
          * [Example](https://www.ssw.com.au/industry/educational):  
          
          (H1) SSW Educational  
          
          (H2) Overview  
          
          (H2) How SSW can help: Customized technology solutions


      **Images** – Under each image, note the caption and alt text (describes the image to search engines)  
      
      Tip: Use an [alt text generator](https://alttext.in/)

          * Example:  
          
          Image - <cat-flying.jpg>  
          
          Caption - Figure: A cat soars majestically above New York City.  
          
          Alt text - cat flying above city  
  

      **Text** - where possible, add links or hyperlinks to relevant SSW pages. 'Internal linking' gives pages credibility for search engines.  

          * Example:  
          
          We are experts in [Power BI](https://www.ssw.com.au/consulting/power-bi). Our developers are also experienced in [database development](https://www.ssw.com.au/consulting/database-development).
     "
      placeholder: "{{ YOUR PAGE CONTENT }}"
      value:
    validations:
      required: true
