query contentQuery($relativePath: String!) {
  ...LayoutQueryFragment
  page(relativePath: $relativePath) {
    ...PageParts
  }
}

query consultingContentQuery($relativePath: String!) {
  ...LayoutQueryFragment
  consulting(relativePath: $relativePath) {
    ...ConsultingParts
  }
}