query contentQuery($relativePath: String!) {
  ...LayoutQueryFragment
  page(relativePath: $relativePath) {
    ...PageParts
  }
}

query consultingContentQuery($relativePath: String!) {
  ...LayoutQueryFragment
  consulting(relativePath: $relativePath) {
    ...ConsultingParts
  }
}

query officeContentQuery($relativePath: String!) {
  ...LayoutQueryFragment
  offices(relativePath: $relativePath) {
    ...OfficesParts
  }
}

query allTestimonialsQuery {
  testimonialsConnection {
    Testimonials: edges {
      Testimonial: node {
        name,
        avatar,
        body,
        company,
        rating
      }
    }
  }
}
query technologyCardContentQuery($cardNames: [String!]) {
  ...LayoutQueryFragment
  technologiesConnection(filter: {name: {in: $cardNames}}) {
    edges {
      node {
        ... on Technologies {
          name
          readMoreSlug
          thumbnail
          body
        }
      }
    }
  }
}
