fragment LayoutQueryFragment on Query {
  global(relativePath: "index.json") {
    ...GlobalParts
  }
  megamenu(relativePath: "menu.json") {
    ...MegamenuParts
  }
}

fragment GetCalendarEventsParts on EventsCalendarConnection {
      pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...EventsCalendarParts
      }
    }
}