fragment LayoutQueryFragment on Query {
  global(relativePath: "index.json") {
    ...GlobalParts
  }
  megamenu(relativePath: "menu.json") {
    ...MegamenuParts
  }
  phishingBanner(relativePath: "banner.json") {
    ...PhishingBannerParts
  }
}

fragment UserGroupParts on EventsCalendarConnection {
  edges {
    node {
      title
      url
      thumbnail
      thumbnailDescription
      presenterName
      presenterProfileUrl
      startDateTime
      endDateTime
      startShowBannerDateTime
      endShowBannerDateTime
      presenterList {
        presenter {
          ... on Presenter {
            profileImg
            torsoImg
            presenter {
              name
              peopleProfileURL
            }
          }
        }
      }
      youTubeId
    }
  }
}

fragment GetArticleParts on ArticlesConnection {
  pageInfo {
    hasPreviousPage
    hasNextPage
    startCursor
    endCursor
  }
  totalCount
  edges {
    cursor
    node {
      ... on Document {
        _sys {
          filename
          basename
          breadcrumbs
          path
          relativePath
          extension
        }
        id
      }
      ...ArticlesParts
    }
  }
}

fragment GetCalendarEventsParts on EventsCalendarConnection {
  pageInfo {
    hasPreviousPage
    hasNextPage
    startCursor
    endCursor
  }
  totalCount
  edges {
    cursor
    node {
      ... on Document {
        _sys {
          filename
          basename
          breadcrumbs
          path
          relativePath
          extension
        }
        id
      }
      ...EventsCalendarParts
    }
  }
}
