name: "Coverage"
on:
  pull_request:
    branches:
      - main

permissions:
  checks: write
  pull-requests: write
  contents: write

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        run: npm install -g pnpm

      - uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          package-manager: pnpm
          test-script: pnpm test
          coverage-file: report.json
          working-directory: /
