name: Delete - Docker image from ACR

on:
  workflow_call:
    inputs:
      imageTags:
        type: string
        description: "Image Tags or PR numbers"
        required: true
  workflow_dispatch:
    inputs:
      imageTag:
        description: "Images Tag or PR number"
        required: true

defaults:
  run:
    shell: pwsh

env:
  IMAGE_TAG: ${{ inputs.imageTags || inputs.imageTag }}
  PREFIX: pr-
permissions:
  id-token: write
  contents: read

jobs:
  delete-acr-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        IMAGE_TAG: ${{ fromJson(inputs.imageTags) }}

    steps:
      - uses: actions/checkout@v4

      - name: Load .env file
        uses: xom9ikk/dotenv@v2
        with:
          path: ./.github

      - name: Azure CLI - Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: ACR - Login
        run: |
          az acr login --name ${{ env.ACR_LOGIN_SERVER }}

      - name: ACR - Delete image
        run: |
          if('${{ matrix.IMAGE_TAG }}'.Length -le 4) # PR tags contain 4 digits
          {
            $imageTagWithPrefix = '${{ env.PREFIX }}${{ matrix.IMAGE_TAG}}'
          }else{
            $imageTagWithPrefix = '${{ matrix.IMAGE_TAG }}'
          }

          # Get the digest of the specific tag
          $digest = az acr repository show-manifests --name ${{ env.ACR_NAME }} `
          --repository ${{ env.IMAGE_NAME }} --output json `
          --query "[?tags.contains('$imageTagWithPrefix')].digest" --output tsv

          # Delete the digest (and all associated tags)
          az acr repository delete --name ${{ env.ACR_NAME }} `
          --image ${{ env.IMAGE_NAME }} --digest $digest --yes

          Write-Output "✅ ACR - image deleted with $digest digest"
