name: Main - Infra - Build and deploy

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/main-infra.yml'
      - 'infra/**'
  workflow_dispatch:

concurrency: 
  group: main-infra
  cancel-in-progress: true

defaults:
  run:
    shell: pwsh

env:
  bicepPath: ./infra/main.bicep

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v3

    - name: Build
      run: |
        az bicep build --file ${{ env.bicepPath }}

    - name: Azure CLI - Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy
      run: |
        $timestamp = (Get-Date -Format yyyy-MM-ddTHH-mm)

        az group create `
          --location ${{ vars.AZURE_RESOURCE_GROUP_LOCATION }} `
          --name ${{ vars.AZURE_RESOURCE_GROUP }}

        az deployment group create `
          --name $timestamp `
          --resource-group ${{ vars.AZURE_RESOURCE_GROUP }} `
          --template-file ${{ env.bicepPath }}
