name: Main - Run Tests

on:
  workflow_run:
    workflows: ["Main - build and deploy"]
    types:
      - completed

jobs:
  on-success:
    runs-on: ubuntu-latest
    steps:
      - name: Run Playwright Tests
        uses: ./.github/workflows/template-ui-tests.yml
        with:
          deploy_url: ${{ 'https://ssw.com.au' }}
      - name: Send failure email for UI tests
        if: ${{ failure() }}
        uses: ./.github/workflows/template-alert-failure.yml
        with:
          subject: SSW Website - UI Tests Failed
          body: |
            The UI tests for deployment ${{ github.event.workflow_run.run_number }} failed. Please check the logs at 
            ${{ github.event.workflow_run.html_url }}

  on-failure:
    name: Send failure email
    uses: ./.github/workflows/template-alert-failure.yml
    with:
      subject: SSW Website - Deployment Failed
      body: |
        The deployment ${{ github.event.workflow_run.run_number }} failed. Please check the logs at 
        ${{ github.event.workflow_run.html_url }}
