name: Deploy - Send Failure Email

on:
  workflow_call:
    inputs:
      subject:
        type: string
        required: true
      body:
        type: string
        required: true

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Stub
        run: echo "Stub"
