name: Template - Re-tag docker image

on:
  workflow_call:
    inputs:
      old_tag:
        type: string
        required: true
      new_tag:
        type: string
        required: true
    secrets:
      AZURE_CREDENTIALS:
        required: true

defaults:
  run:
    shell: pwsh

jobs:
  re-tag-image:
    runs-on: ubuntu-latest
    steps:

    - name: Azure CLI - Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: ACR - Login
      run: |
        az acr login --name ${{ vars.ACR_LOGIN_SERVER }}

    - uses: shrink/actions-docker-registry-tag@v3
      with:
        registry: ${{ vars.ACR_LOGIN_SERVER }}
        repository: ${{ vars.IMAGE_NAME }}
        target: ${{ inputs.old_tag }}
        tags: |
          ${{ inputs.new_tag }}