name: Deploy - Send Failure Email

on:
  workflow_call:
    inputs:
      subject:
        type: string
        required: true
      body:
        type: string
        required: true

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Send email
        uses: dawidd6/action-send-mail@v2.0.0
        with:
          server_address: ${{ secrets.EMAIL_SERVER }}
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME}}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: ${{ inputs.subject }}
          body: ${{ inputs.body }}
          to: harryross@ssw.com.au
          from: GitHub Exploded
