name: Get workflow run for feature branch

on:
  pull_request:
    branches:
      - main

jobs:
  get-actions:
    name: Get repository actions
    runs-on: ubuntu-latest
    permissions:
      actions: read
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Get actions
        shell: pwsh
        run: |
          $owner = "SSWConsulting"
          $repo = "SSW.Website"
          $url = "https://api.github.com/repos/$owner/$repo/actions/workflows/45437805/runs"
          $artifactName = "bundle-analyze-artifact"

          $headers = @{
            "Authorization" = "Bearer $env:GITHUB_TOKEN"
            "Content-Type" = "application/json"
          }

          $queryParams = @{
            "status" = "completed"
            "conclusion" = "success"
            "per_page" = 1
          }

          $response = Invoke-RestMethod -Uri $url -Headers $headers -Body $queryParams -Method Get

          if ($response.total_count -gt 0) {
            $latestRun = $response.workflow_runs[0]

            Write-Host "Workflows in $owner/$repo"
            Write-Host "----------------------------------------"

            # Loop through each workflow and display details
            foreach ($workflow in $response.workflows) {
              Write-Host "Latest successful workflow run:"
              Write-Host "----------------------------------------"
              Write-Host "Run ID: $($latestRun.id)"
              Write-Host "Status: $($latestRun.status)"
              Write-Host "Conclusion: $($latestRun.conclusion)"
              Write-Host "Artifacts URL: $($latestRun.artifacts_url)"
              Write-Host "Run URL: $($latestRun.html_url)"
              Write-Host "----------------------------------------"

              $artifactsUrl = "https://api.github.com/repos/$owner/$repo/actions/runs/$($latestRun.id)/artifacts"
              $artifactsResponse = Invoke-RestMethod -Uri $artifactsUrl -Headers $headers -Method Get

              if ($artifactsResponse.total_count -gt 0) {
                Write-Host "Artifacts for run $($latestRun.id)"
                Write-Host "----------------------------------------"

                # Find the artifact by name
                $artifact = $artifactsResponse.artifacts | Where-Object { $_.name -eq $artifactName }

                if ($artifact) {
                  Write-Host "Artifact found:"
                  Write-Host "Artifact ID: $($artifact.id)"
                  Write-Host "Name: $($artifact.name)"
                  Write-Host "Size: $($artifact.size_in_bytes) bytes"
                  Write-Host "Download URL: $($artifact.archive_download_url)"
                  Write-Host "----------------------------------------"
                } else {
                  Write-Host "No artifact found with name '$artifactName'."
                }
              } else {
                Write-Host "No artifacts found for run $($latestRun.id)."
              }
            }
          } else {
              Write-Host "No workflows found in $owner/$repo."
          }
